pipeline {
    agent any

    environment {
        IMAGE_NAME = "mosad/app"     // غيّرها لو ليك Repo مختلف
        TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Build Image') {
            steps {
                script {
                    buildImage(IMAGE_NAME, TAG)
                }
            }
        }

        stage('Scan Image') {
            steps {
                script {
                    scanImage(IMAGE_NAME, TAG)
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                script {
                    pushImage(IMAGE_NAME, TAG)
                }
            }
        }

        stage('Delete Local Image') {
            steps {
                script {
                    deleteLocalImage(IMAGE_NAME, TAG)
                }
            }
        }

        stage('Update Manifests') {
            steps {
                script {
                    updateManifest(TAG)    // اسم الفانكشن بناءً على اسم الفايل عندك
                }
            }
        }

        stage('Push Manifests') {
            steps {
                script {
                    pushManifests()
                }
            }
        }
    }
}
