pipeline {
    agent any

    environment {
        DOCKERHUB_USER = "mosaad71298"
        IMAGE_NAME     = "nti-devops-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Image') {
            steps {
                sh """
                    docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} .
                """
            }
        }

        stage('Scan Image (Trivy)') {
            when {
                expression { return false }   // Disable (BONUS: enable later)
            }
            steps {
                sh """
                    trivy image ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh """
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                    """
                }
            }
        }

        stage('Delete Image Locally') {
            steps {
                sh """
                    docker rmi ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }

        stage('Update Manifests') {
            steps {
                script {
                    updateManifest("${BUILD_NUMBER}")
                }
            }
        }

        stage('Push Manifests') {
            steps {
                sh """
                    git push origin main
                """
            }
        }
    }
}

